package telas.interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telas.conexion.Conexion;

public class InterfazTelas extends javax.swing.JFrame {

	private static int id;
	private static int fila;
	private static int filasAfectadas;
	private static String nombre;
	private static String tipo;
	private static String color;
	private static String tamanoStr;
	private static String precioStr;
	private static double tamano;
	private static double precio;
	private static String sql;
	private final Conexion con;
	Connection cn = null;
	PreparedStatement ps = null;
	ResultSet rs = null;

	public InterfazTelas() {
		initComponents();
		this.setLocationRelativeTo(null);
		con = new Conexion();
		cn = con.getConnection();
		if (cn != null) {
			btnConsultarActionPerformed(null);
		} else {
			JOptionPane.showMessageDialog(null, "Base de datos no conectada.", "Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                JLabelTitulo = new javax.swing.JLabel();
                btnInsertar = new javax.swing.JButton();
                btnConsultar = new javax.swing.JButton();
                btnActualizar = new javax.swing.JButton();
                btnEliminar = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                JTableBaseDatos = new javax.swing.JTable();
                JTextNombre = new javax.swing.JTextField();
                JTextTipo = new javax.swing.JTextField();
                JTextColor = new javax.swing.JTextField();
                jTextTamano = new javax.swing.JTextField();
                jTextPrecio = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jButtonSalidas = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();
                btnHistorialVentas = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                JLabelTitulo.setText("Menu CRUD");

                btnInsertar.setText("Insertar");
                btnInsertar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnInsertarActionPerformed(evt);
                        }
                });

                btnConsultar.setText("Consultar");
                btnConsultar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConsultarActionPerformed(evt);
                        }
                });

                btnActualizar.setText("Actualizar");
                btnActualizar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnActualizarActionPerformed(evt);
                        }
                });

                btnEliminar.setText("Eliminar");
                btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarActionPerformed(evt);
                        }
                });

                JTableBaseDatos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null}
                        },
                        new String [] {
                                "ID", "Nombre", "Tipo", "Color", "Cantidad", "Precio"
                        }
                ));
                jScrollPane1.setViewportView(JTableBaseDatos);

                jLabel1.setText("Nombre:");

                jLabel2.setText("Tipo:");

                jLabel3.setText("Color:");

                jLabel4.setText("Cantidad");

                jLabel5.setText("Precio:");

                jButtonSalidas.setText("Salidas");
                jButtonSalidas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonSalidasActionPerformed(evt);
                        }
                });

                jLabel6.setText("Comprar tela");

                btnHistorialVentas.setText("Historial Ventas");
                btnHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHistorialVentasActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(JLabelTitulo))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel5))
                                                                .addGap(41, 41, 41)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(JTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(JTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(JTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(81, 81, 81)
                                                                .addComponent(btnActualizar)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(btnInsertar)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(105, 105, 105)
                                                                                .addComponent(btnConsultar)
                                                                                .addGap(84, 84, 84)
                                                                                .addComponent(btnEliminar)
                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addGap(18, 18, 18)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonSalidas)
                                                        .addComponent(jLabel6))
                                                .addGap(52, 52, 52))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnHistorialVentas)
                                                .addGap(23, 23, 23))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelTitulo)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnEliminar)
                                                .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(JTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(13, 13, 13)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(JTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(JTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(btnActualizar))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addGap(0, 12, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonSalidas)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btnHistorialVentas)
                                                                .addGap(35, 35, 35)))
                                                .addComponent(btnInsertar)
                                                .addGap(132, 132, 132))))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	//Boton que se utiliza para insertar en la base de Datos
        private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

		// Obtener datos de los campos de texto
		nombre = JTextNombre.getText();
		tipo = JTextTipo.getText();
		color = JTextColor.getText();
		tamanoStr = jTextTamano.getText();
		precioStr = jTextPrecio.getText();

		// Validación básica
		if (nombre.isEmpty() || tipo.isEmpty() || color.isEmpty() || tamanoStr.isEmpty() || precioStr.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
			return;
		}

		try {
			tamano = Double.parseDouble(tamanoStr);
			precio = Double.parseDouble(precioStr);

			sql = "INSERT INTO telas (nombre, tipo, color, tamano, precio_metro) VALUES (?, ?, ?, ?, ?)";

			ps = cn.prepareStatement(sql);

			ps.setString(1, nombre);
			ps.setString(2, tipo);
			ps.setString(3, color);
			ps.setDouble(4, tamano);
			ps.setDouble(5, precio);

			filasAfectadas = ps.executeUpdate();

			if (filasAfectadas > 0) {
				JOptionPane.showMessageDialog(null, "Registro agregado con éxito.");
				limpiarCampos();
				btnConsultarActionPerformed(evt);
			}

		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "Error: Tamaño y Precio deben ser valores numéricos.");
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error SQL al insertar: " + e.getMessage());
		}
        }//GEN-LAST:event_btnInsertarActionPerformed

	//Boton que se usa para hacer la consulta a la base de Datos
        private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

		sql = "SELECT id_tela, nombre, tipo, color, tamano, precio_metro FROM telas";
		DefaultTableModel modelo = new DefaultTableModel();

		try {
			ps = cn.prepareStatement(sql);
			rs = ps.executeQuery();

			// define las columnas
			modelo.addColumn("ID");
			modelo.addColumn("Nombre");
			modelo.addColumn("Tipo");
			modelo.addColumn("Color");
			modelo.addColumn("Cantidad");
			modelo.addColumn("Precio/m");
			JTableBaseDatos.setModel(modelo);

			// Se llenan filas
			Object[] filas = new Object[6];
			while (rs.next()) {
				filas[0] = rs.getInt("id_tela");
				filas[1] = rs.getString("nombre");
				filas[2] = rs.getString("tipo");
				filas[3] = rs.getString("color");
				filas[4] = rs.getDouble("tamano");
				filas[5] = rs.getDouble("precio_metro");
				modelo.addRow(filas);
			}

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error al consultar la base de datos: " + e.getMessage());
		}

        }//GEN-LAST:event_btnConsultarActionPerformed

	//Boton que nos va a permitir hacer la elimicacion de una fila en la base
        private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

		fila = JTableBaseDatos.getSelectedRow();
		if (fila == -1) {
			JOptionPane.showMessageDialog(null, "Debe seleccionar la fila a eliminar.");
			return;
		}
		// Obtener la ID del registro seleccionado (siempre columna 0)
		int idAEliminar = (int) JTableBaseDatos.getValueAt(fila, 0);

		int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la ID " + idAEliminar + "?",
			"Confirmar", JOptionPane.YES_NO_OPTION);

		if (confirmacion == JOptionPane.YES_OPTION) {
			sql = "DELETE FROM telas WHERE id_tela=?";

			try {
				ps = cn.prepareStatement(sql);
				ps.setInt(1, idAEliminar);

				filasAfectadas = ps.executeUpdate();

				if (filasAfectadas > 0) {
					JOptionPane.showMessageDialog(null, "Registro ID " + idAEliminar + " eliminado con éxito.");
					btnConsultarActionPerformed(evt);
				}
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(null, "Error SQL al eliminar: " + e.getMessage());
			}
		}
        }//GEN-LAST:event_btnEliminarActionPerformed

	//Boton que se utiliza para la actualizacion de la base de datos telas
        private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

		fila = JTableBaseDatos.getSelectedRow();

		if (fila == -1) {
			JOptionPane.showMessageDialog(null, "Debe seleccionar la fila a modificar primero.");
			return;
		}
		// Obtener la ID del registro seleccionado
		id = (int) JTableBaseDatos.getValueAt(fila, 0);

		// Obtener los nuevos valores de los campos 
		nombre = JTextNombre.getText();
		tipo = JTextTipo.getText();
		color = JTextColor.getText();

		try {
			tamano = Double.parseDouble(jTextTamano.getText());
			precio = Double.parseDouble(jTextPrecio.getText());

			sql = "UPDATE telas SET nombre=?, tipo=?, color=?, tamano=?, precio_metro=? WHERE id_tela=?";

			ps = cn.prepareStatement(sql);

			ps.setString(1, nombre);
			ps.setString(2, tipo);
			ps.setString(3, color);
			ps.setDouble(4, tamano);
			ps.setDouble(5, precio);
			ps.setInt(6, id);

			filasAfectadas = ps.executeUpdate();

			if (filasAfectadas > 0) {
				JOptionPane.showMessageDialog(null, "Registro ID " + id + " modificado con éxito.");
				limpiarCampos();
				btnConsultarActionPerformed(evt);
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "Error: Valores de tamaño y precio no son válidos.");
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error SQL al actualizar: " + e.getMessage());
		}
        }//GEN-LAST:event_btnActualizarActionPerformed

        private void jButtonSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidasActionPerformed

		Salida segundaVentana = new Salida(this, true);

		segundaVentana.setVisible(true);
		segundaVentana.setLocation(900, 500);
		segundaVentana.dispose();
		btnConsultarActionPerformed(evt);


        }//GEN-LAST:event_jButtonSalidasActionPerformed

        private void btnHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentasActionPerformed


		DefaultTableModel modelo = new DefaultTableModel();
		sql = "SELECT "
			+ "v.id_venta, v.fecha_venta, d.metros_vendidos, d.precio_unitario, d.subtotal, t.nombre "
			+ "FROM ventas v "
			+ "JOIN detalle_venta d ON v.id_venta = d.id_venta "
			+ "JOIN telas t ON d.id_tela = t.id_tela "
			+ "ORDER BY v.id_venta DESC, t.nombre"; // Ordenamos por Venta más reciente

		// limpiar la tabla que tiene la consulta 
		int rowCount = modelo.getRowCount();
		for (int i = rowCount - 1; i >= 0; i--) {
			modelo.removeRow(i);
		}

		modelo.setColumnCount(0);

		modelo.addColumn("ID Venta");
		modelo.addColumn("Fecha");
		modelo.addColumn("Producto");
		modelo.addColumn("Metros");
		modelo.addColumn("Precio Unit.");
		modelo.addColumn("Subtotal");
		JTableBaseDatos.setModel(modelo);

		try (PreparedStatement psHistorial = cn.prepareStatement(sql); ResultSet rsHistorial = psHistorial.executeQuery()) {

			//Llenar filas
			while (rsHistorial.next()) {
				Object[] row= new Object[6];
				row[0] = rsHistorial.getInt("id_venta");
				row[1] = rsHistorial.getTimestamp("fecha_venta");
				row[2] = rsHistorial.getString("nombre"); // Nombre de la tela
				row[3] = rsHistorial.getDouble("metros_vendidos");
				row[4] = rsHistorial.getDouble("precio_unitario");
				row[5] = rsHistorial.getDouble("subtotal");

				modelo.addRow(row);
			}

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, "Error al cargar el historial de ventas: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
		}

        }//GEN-LAST:event_btnHistorialVentasActionPerformed

	private void limpiarCampos() {
		JTextNombre.setText("");
		JTextTipo.setText("");
		JTextColor.setText("");
		jTextTamano.setText("");
		jTextPrecio.setText("");
		JTextNombre.requestFocus();
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel JLabelTitulo;
        private javax.swing.JTable JTableBaseDatos;
        private javax.swing.JTextField JTextColor;
        private javax.swing.JTextField JTextNombre;
        private javax.swing.JTextField JTextTipo;
        private javax.swing.JButton btnActualizar;
        private javax.swing.JButton btnConsultar;
        private javax.swing.JButton btnEliminar;
        private javax.swing.JButton btnHistorialVentas;
        private javax.swing.JButton btnInsertar;
        private javax.swing.JButton jButtonSalidas;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextPrecio;
        private javax.swing.JTextField jTextTamano;
        // End of variables declaration//GEN-END:variables
}
