package telas.interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import telas.conexion.Conexion;

public class Salida extends javax.swing.JDialog {

	private static int idSeleccionado;
	private static String nombreSeleccionado;
	private static String inputCantidad;
	private static int id;
	//private static int filasAfectadas;
	private static int idOrden;
	private static double metrosAVender;
	private static double stockActual;
	private static double precioUnitario;
	//private static double totalAPagar;
	private static double stock;
	private static double totalGeneral;
	private static String nombre;
	private static String sql;
	private final Conexion con;
	Connection cn = null;
	PreparedStatement ps = null;
	ResultSet rs = null;
	private final java.util.Map<String, Integer> telaMap = new java.util.HashMap<>();
	private final java.util.List<DetalleCompra> listaCompras = new java.util.ArrayList<>();
	private record DetalleCompra(int idTela, String nombreTela, double metros, double precioUnitario, double subtotal) {
	}

	public Salida(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
		con = new Conexion();
		cn = con.getConnection();
		if (cn != null) {
			llenarComboBoxTelas();
		} else {
			JOptionPane.showMessageDialog(null, "Base de datos no conectada.", "Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jComboBox1 = new javax.swing.JComboBox<>();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextAreaRecibo = new javax.swing.JTextArea();
                jTextCantidadVenta = new javax.swing.JTextField();
                btnAceptarVenta = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btnImprimirRecibo = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                jTextAreaRecibo.setColumns(20);
                jTextAreaRecibo.setRows(5);
                jScrollPane1.setViewportView(jTextAreaRecibo);

                btnAceptarVenta.setText("Ok");
                btnAceptarVenta.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarVentaActionPerformed(evt);
                        }
                });

                jLabel1.setText("Cantidad");

                jLabel2.setText("Elige un tipo de tela: ");

                btnImprimirRecibo.setText("Finalizar compra");
                btnImprimirRecibo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnImprimirReciboActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(128, 128, 128))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnImprimirRecibo)))
                                                .addGap(15, 15, 15))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(jTextCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                                .addComponent(btnAceptarVenta)
                                                .addContainerGap())))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAceptarVenta))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnImprimirRecibo)
                                .addGap(20, 20, 20))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

		if (jComboBox1.getSelectedItem() != null) {
			nombreSeleccionado = (String) jComboBox1.getSelectedItem();
			// Opcional: Mostrar el stock disponible en una etiqueta (jLabelStock)
			idSeleccionado = telaMap.get(nombreSeleccionado);
			//double stock = obtenerStockActual(idSeleccionado);
			btnAceptarVenta.setEnabled(true); //habilitar el boton de aceptar
			jTextCantidadVenta.requestFocus();
		}
        }//GEN-LAST:event_jComboBox1ActionPerformed

        private void btnAceptarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarVentaActionPerformed

		// 1. Obtener valores (Se mantiene tu código)
		inputCantidad = jTextCantidadVenta.getText();
		nombreSeleccionado = (String) jComboBox1.getSelectedItem();

		if (nombreSeleccionado == null) {
			JOptionPane.showMessageDialog(this, "Debe seleccionar una tela.", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		if (inputCantidad.trim().isEmpty()) {
			JOptionPane.showMessageDialog(this, "La cantidad no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
			jTextCantidadVenta.requestFocus();
			return;
		}

		try {
			//Parsar y Obtener datos
			metrosAVender = Double.parseDouble(inputCantidad.trim());
			idSeleccionado = telaMap.get(nombreSeleccionado);

			// Validaciones de cantidad y Stock
			if (metrosAVender <= 0) {
				JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero.", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}

			stockActual = obtenerStockActual(idSeleccionado);

			if (metrosAVender > stockActual) {
				JOptionPane.showMessageDialog(this,
					"Stock insuficiente. Disponible: " + stockActual + "m",
					"Error de Stock", JOptionPane.WARNING_MESSAGE);
				return;
			}

			//Obtener Precio 
			precioUnitario = obtenerPrecioMetro(idSeleccionado);
			double subtotal = metrosAVender * precioUnitario;

			DetalleCompra nuevaLinea = new DetalleCompra(
				idSeleccionado,
				nombreSeleccionado,
				metrosAVender,
				precioUnitario,
				subtotal
			);
			listaCompras.add(nuevaLinea);

			mostrarComprasTemporales(); // Muestra el carrito actual en el JTextArea
			jTextCantidadVenta.setText(""); // Limpiar el campo
			jTextCantidadVenta.requestFocus(); // Enfocar para la siguiente compra

			btnImprimirRecibo.setEnabled(true);

		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this,
				"Ingresa solo números válidos para la cantidad.",
				"Error de Formato", JOptionPane.ERROR_MESSAGE);
			jTextCantidadVenta.setText("");
			jTextCantidadVenta.requestFocus();
		}
        }//GEN-LAST:event_btnAceptarVentaActionPerformed

        private void btnImprimirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirReciboActionPerformed

		if (listaCompras.isEmpty()) {
			JOptionPane.showMessageDialog(this, "No hay productos en el carrito.", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		int idCompra = generarIdCompra();

		if (idCompra == -1) {
			return; 
		}

		String sqlUpdateStock = "UPDATE telas SET tamano = tamano - ? WHERE id_tela = ? AND tamano >= ?";
		String sqlInsertDetalle = "INSERT INTO detalle_venta (id_venta, id_tela, metros_vendidos, precio_unitario, subtotal) VALUES (?, ?, ?, ?, ?)";

		StringBuilder recibo = new StringBuilder();
		totalGeneral = 0; 

		recibo.append("=========================================\n");
		recibo.append(String.format("          RECIBO FINAL #%d\n", idCompra));
		recibo.append("=========================================\n");

		try (PreparedStatement psStock = cn.prepareStatement(sqlUpdateStock); PreparedStatement psDetalle = cn.prepareStatement(sqlInsertDetalle)) {

			for (DetalleCompra detalle : listaCompras) {

				psStock.setDouble(1, detalle.metros());
				psStock.setInt(2, detalle.idTela());
				psStock.setDouble(3, detalle.metros());
				int stockAfectado = psStock.executeUpdate();

				if (stockAfectado > 0) {
					psDetalle.setInt(1, idCompra); 
					psDetalle.setInt(2, detalle.idTela());
					psDetalle.setDouble(3, detalle.metros());
					psDetalle.setDouble(4, detalle.precioUnitario());
					psDetalle.setDouble(5, detalle.subtotal());
					psDetalle.executeUpdate();

					totalGeneral += detalle.subtotal();
					recibo.append(String.format("%s\n", detalle.nombreTela()));
					recibo.append(String.format("  %.2f m @ $%.2f = $%.2f\n",
						detalle.metros(), detalle.precioUnitario(), detalle.subtotal()));
					recibo.append("-----------------------------------------\n");
				} else {
					recibo.append(String.format("[FALLÓ STOCK] %s: No registrado.\n", detalle.nombreTela()));
				}
			}

			recibo.append(String.format("\nTOTAL A PAGAR: $%.2f\n", totalGeneral));
			recibo.append("=========================================\n");

			jTextAreaRecibo.setText(recibo.toString());
			listaCompras.clear(); 
			btnImprimirRecibo.setEnabled(false); 

		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, "Error durante la transacción de venta: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
		}
        }//GEN-LAST:event_btnImprimirReciboActionPerformed

	private void mostrarComprasTemporales() {
		if (listaCompras.isEmpty()) {
			jTextAreaRecibo.setText("El carrito está vacío. Añade una tela.");
			return;
		}

		StringBuilder sb = new StringBuilder();
		double totalAcumulado = 0;

		sb.append("=====================================\n");
		sb.append("        COMPRAS ACTUALES\n");
		sb.append("=====================================\n");

		for (int i = 0; i < listaCompras.size(); i++) {
			DetalleCompra d = listaCompras.get(i);
			totalAcumulado += d.subtotal();

			sb.append(String.format("Ítem %d: %s\n", (i + 1), d.nombreTela()));
			sb.append(String.format("  Cantidad: %.2f m | Subtotal: $%.2f\n", d.metros(), d.subtotal()));
			sb.append("-------------------------------------\n");
		}

		sb.append(String.format("\nTotal actual : $%.2f\n", totalAcumulado));
		sb.append("=====================================\n");

		jTextAreaRecibo.setText(sb.toString());
		jTextAreaRecibo.setCaretPosition(0);
	}

	private int generarIdCompra() {
		// Calcular el total de la lista temporal
		 totalGeneral = listaCompras.stream()
			.mapToDouble(DetalleCompra::subtotal)
			.sum();

		sql = "INSERT INTO ventas (fecha_venta, total_venta) VALUES (NOW(), ?)";
		idOrden = -1;

		try (PreparedStatement psVenta = cn.prepareStatement(sql,
			PreparedStatement.RETURN_GENERATED_KEYS)) {

			psVenta.setDouble(1, totalGeneral);
			psVenta.executeUpdate();

			try (ResultSet rsId = psVenta.getGeneratedKeys()) {
				if (rsId.next()) {
					idOrden = rsId.getInt(1); // Esta es la ID única de la compra
				}
			}
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, "Error al generar ID de Compra: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
		}
		return idOrden;
	}

	private void llenarComboBoxTelas() {
		sql = "SELECT id_tela, nombre FROM telas";

		java.awt.event.ActionListener[] listeners = jComboBox1.getActionListeners();
		//  se remueven temporalmente
		for (java.awt.event.ActionListener l : listeners) {
			jComboBox1.removeActionListener(l);
		}
		try {
			ps = cn.prepareStatement(sql);
			rs = ps.executeQuery();

			// limpia la lista visual y los ids
			jComboBox1.removeAllItems();
			telaMap.clear();

			while (rs.next()) {
				id = rs.getInt("id_tela");
				nombre = rs.getString("nombre");

				//mostrara el nombre de la tela
				jComboBox1.addItem(nombre);

				// Guardo los dos datos en el map
				telaMap.put(nombre, id);
			}

		} catch (SQLException e) {
		}
	}
	
	private double obtenerStockActual(int idTela) {

		sql = "SELECT tamano FROM telas WHERE id_tela = ?";
		stock = 0;

		try {
			cn = con.getConnection();
			ps = cn.prepareStatement(sql);
			ps.setInt(1, idTela);
			rs = ps.executeQuery();

			if (rs.next()) {
				stock = rs.getDouble("tamano");
			}
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error al verificar stock: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
		}
		return stock;
	}

	// Método para obtener el precio
	private double obtenerPrecioMetro(int idTela) {

		sql = "SELECT precio_metro FROM telas WHERE id_tela = ?";
		double precio = 0;

		try {
			ps = cn.prepareStatement(sql);
			ps.setInt(1, idTela);
			rs = ps.executeQuery();

			if (rs.next()) {
				precio = rs.getDouble("precio_metro");
			}
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error al obtener precio: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
		}
		return precio;
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAceptarVenta;
        private javax.swing.JButton btnImprimirRecibo;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextAreaRecibo;
        private javax.swing.JTextField jTextCantidadVenta;
        // End of variables declaration//GEN-END:variables
}
